version: '3.1'
services:

  # first
  zoo1:
    image: zookeeper:3.5
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./zoo-conf/zoo.cfg.1:/conf/zoo.cfg
  exp1:
    image: dabealu/zookeeper-exporter
    ports:
      - 8081:8080
    command: --zk-host=zoo1

  # second
  zoo2:
    image: zookeeper:3.5
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
    volumes:
      - ./zoo-conf/zoo.cfg.2:/conf/zoo.cfg
  exp2:
    image: dabealu/zookeeper-exporter
    ports:
      - 8082:8080
    command: --zk-host=zoo2

  # third
  zoo3:
    ##### Uncomment block below and comment 'image' parameter in order to test timeout
    # build:
    #   context: zoo-timeout
    # privileged: true  # Needed for iptables drop rule to work in custom entrypoint script
    ##### End
    image: zookeeper:3.5
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./zoo-conf/zoo.cfg.3:/conf/zoo.cfg
  exp3:
    image: dabealu/zookeeper-exporter
    ports:
      - 8083:8080
    command: --zk-host=zoo3 --timeout=5

  exp123:
    image: dabealu/zookeeper-exporter
    ports:
      - 8084:8080
    command: --zk-list="zoo1:2181,zoo2:2181,zoo3:2181" --timeout=5
